version: '3.7'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    # volumes:
    #   - .mongodb:/data/db ## TODO: there is an issue with the volume!
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-network
        
  api:
    image: ordermanagement-api
    build:
      context: .
      dockerfile: src/OrderManagement.Api/Dockerfile
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge